spryk: method
description: 'Adds a Client dependency method to the *module*DependencyProvider.'
mode: both
deprecated: 'Use AddDependencyBridgeMethod instead.'
arguments:
    module:
        inherit: true
    dependentModule:
        inherit: true
    organization:
        inherit: true
        default: Spryker
    providerMethod:
        inherit: true
        value: 'add{{ dependentModule }}Client'
    template:
        value: Glue/Dependency/Client/GlueDependencyClientDependencyProviderMethod.php.twig
    target:
        value: '{{ organization }}\Glue\{{ module }}\{{ module }}DependencyProvider'
preSpryks:
    - AddGlueDependencyProvider
postSpryks:
    -
        AddGlueDependencyClientDependencyProviderConstant:
            arguments:
                name: 'CLIENT_{{ dependentModule | underscored | upper }}'
                value: 'CLIENT_{{ dependentModule | underscored | upper }}'
                visibility: public
    - AddGlueDependencyClientToDependencyProvider
