spryk: template
description: "Adds a new Request mapper that maps GlueRequest objects to ResourceDataObject transfers."
mode: both
level: 2

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    className:
        value: "GlueRequest{{ resourceDataObject }}Mapper"

    resource:
        description: "Defines the resource name this controller will work with."

    subDirectory:
        inherit: true
        value: Mapper

    application:
        inherit: true
        value: Glue

    applicationType:
        inherit: true
        description: "Can be one of: Backend or Frontend"
        default: "Backend"

    isTestClass:
        inherit: true
        isOptional: true
        default: false

    resourceDataObject:
        description: "Defines the Transfer that will be used in the Methods. Do not use Transfer as suffix, it will be added automatically. Example: Customer (ok) CustomerTransfer (wrong)"
        isOptional: true # Is not needed for all methods
        value: "{{ resource | normalizeResourceName | singularize }}"

    template:
        value: Common/Class.php.twig

    zedDomainEntity:
        description: "Defines the domainEntity used on Zed side for the CRUD Facade. It will be used to create all needed Transfer Objects."
        value: "{{ resource | normalizeResourceName | singularize }}"

    target:
        value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueRequest{{ resourceDataObject }}Mapper"

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
    - AddGlueBackendApiController
    - AddInterface

postSpryks:
    - AddMethod:
          arguments:
              method:
                  value: "mapGlueRequestTransferTo{{ zedDomainEntity }}CriteriaTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\GlueRequestTransfer $glueRequestTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CriteriaTransfer"
              body:
                  value: Glue/BackendApi/RequestMapper/MapGlueRequestTransferToCriteriaTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueRequest{{ resourceDataObject }}Mapper"
          postSpryks:
              - AddInterfaceMethod:
                    arguments:
                        condition: "visibility === 'public' && withInterface === true"
    - AddMethod:
          arguments:
              method:
                  value: "mapGlueRequestTransferTo{{ zedDomainEntity }}CollectionDeleteCriteriaTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\GlueRequestTransfer $glueRequestTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionDeleteCriteriaTransfer"
              body:
                  value: Glue/BackendApi/RequestMapper/MapGlueRequestTransferToCollectionDeleteCriteriaTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueRequest{{ resourceDataObject }}Mapper"
          postSpryks:
              - AddInterfaceMethod:
                    arguments:
                        condition: "visibility === 'public' && withInterface === true"
    - AddMethod:
          arguments:
              method:
                  value: "mapIdentifierTo{{ zedDomainEntity }}CriteriaTransfer"
              input:
                  value: "int $identifier, \\Generated\\Shared\\Transfer\\GlueRequestTransfer $glueRequestTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CriteriaTransfer"
              body:
                  value: Glue/BackendApi/RequestMapper/MapIdentifierToCriteriaTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueRequest{{ resourceDataObject }}Mapper"
          postSpryks:
              - AddInterfaceMethod:
                    arguments:
                        condition: "visibility === 'public' && withInterface === true"
    - AddMethod:
          arguments:
              method:
                  value: "mapIdentifierTo{{ zedDomainEntity }}CollectionDeleteCriteriaTransfer"
              input:
                  value: "int $identifier, \\Generated\\Shared\\Transfer\\GlueRequestTransfer $glueRequestTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionDeleteCriteriaTransfer"
              body:
                  value: Glue/BackendApi/RequestMapper/MapIdentifierToCollectionDeleteCriteriaTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueRequest{{ resourceDataObject }}Mapper"
          postSpryks:
              - AddInterfaceMethod:
                    arguments:
                        condition: "visibility === 'public' && withInterface === true"
    - AddMethod:
          arguments:
              method:
                  value: "map{{ resourceDataObject }}TransferTo{{ zedDomainEntity }}CollectionRequestTransfer"
              input:
                  value: "\\Generated\\Shared\\Transfer\\{{ resourceDataObject }}Transfer ${{ resourceDataObject | lcfirst }}Transfer, \\Generated\\Shared\\Transfer\\GlueRequestTransfer $glueRequestTransfer"
              output:
                  value: "\\Generated\\Shared\\Transfer\\{{ zedDomainEntity }}CollectionRequestTransfer"
              body:
                  value: Glue/BackendApi/RequestMapper/MapIdentifierToCollectionCollectionRequestTransfer.php.twig
              target:
                  value: "{{ organization }}\\Glue\\{{ module }}\\Mapper\\GlueRequest{{ resourceDataObject }}Mapper"
          postSpryks:
              - AddInterfaceMethod:
                    arguments:
                        condition: "visibility === 'public' && withInterface === true"
    # Add factory method
    - AddGlueFactoryMethod:
          arguments:
              subDirectory:
                  value: "Mapper"
              className:
                  value: "GlueRequest{{ resourceDataObject }}Mapper"
